"""Nested AGENTS.md generator, per ADR-003.

Generated, not hand-authored: `sync_agents_md` derives every nested file
from the same `build_index()` the hook and CLI use, so there is one source
of truth. `check_agents_md` diffs the generated content against what's on
disk and reports drift, so `spec_lint` can fail CI on a stale file.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

from agentcore.specs.index import GOVERNED_ROOTS, build_index, load_specs, spec_file_path

_HEADER = (
    "<!-- AUTO-GENERATED by `forge spec sync-agents-md` — "
    "do not hand-edit; edit the governing spec(s) instead. -->"
)


def _render(directory: str, file_owners: dict[str, str], specs_dir: Path, repo_root: Path) -> str:
    specs = load_specs(specs_dir)
    spec_ids = sorted(set(file_owners.values()))

    lines = [_HEADER, "", f"# {directory}/ — governed by {', '.join(spec_ids)}", ""]
    for spec_id in spec_ids:
        model = specs[spec_id]
        path = spec_file_path(specs_dir, spec_id)
        rel_path = path.relative_to(repo_root).as_posix() if path else "(spec file not found)"
        lines.append(f"- `{spec_id}` — {model.title} (status: {model.status}) — {rel_path}")

    lines.append("")
    lines.append("File -> governing spec:")
    for filename, spec_id in sorted(file_owners.items()):
        lines.append(f"- `{filename}` -> `{spec_id}`")
    lines.append("")

    return "\n".join(lines)


def _owners_by_directory(specs_dir: str | Path, repo_root: str | Path) -> dict[str, dict[str, str]]:
    index = build_index(specs_dir, repo_root)
    by_dir: dict[str, dict[str, str]] = defaultdict(dict)
    for path, spec_id in index.owners.items():
        p = Path(path)
        if p.parts[0] not in GOVERNED_ROOTS or p.name in (".gitkeep", "AGENTS.md"):
            continue
        by_dir[str(p.parent)][p.name] = spec_id
    return by_dir


def sync_agents_md(
    specs_dir: str | Path, repo_root: str | Path, dry_run: bool = False
) -> list[tuple[Path, str]]:
    """Generate (or, if dry_run, just compute) a nested AGENTS.md per
    governed-root directory that owns at least one file. Returns
    (path, content) pairs.
    """
    specs_dir = Path(specs_dir)
    root = Path(repo_root)

    results: list[tuple[Path, str]] = []
    for directory, file_owners in sorted(_owners_by_directory(specs_dir, root).items()):
        content = _render(directory, file_owners, specs_dir, root)
        target = root / directory / "AGENTS.md"
        if not dry_run:
            target.write_text(content)
        results.append((target, content))
    return results


@dataclass(frozen=True)
class StaleAgentsMd:
    path: Path
    reason: str  # "missing" | "outdated"


def check_agents_md(specs_dir: str | Path, repo_root: str | Path) -> list[StaleAgentsMd]:
    """Report nested AGENTS.md files that don't match what sync_agents_md
    would (re)generate — missing, drifted, or no longer needed.
    """
    root = Path(repo_root)
    expected = dict(sync_agents_md(specs_dir, root, dry_run=True))

    stale: list[StaleAgentsMd] = []
    for path, content in expected.items():
        if not path.is_file():
            stale.append(StaleAgentsMd(path, "missing"))
        elif path.read_text() != content:
            stale.append(StaleAgentsMd(path, "outdated"))

    for governed_root in GOVERNED_ROOTS:
        for path in (root / governed_root).rglob("AGENTS.md"):
            if path not in expected:
                stale.append(StaleAgentsMd(path, "orphaned"))

    return stale
